import type { SessionUser } from "../shared/types";

// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
export type AppBindings = Env;

export interface AppVariables {
  user: SessionUser | null;
  sessionId: string | null;
}

export type HonoEnv = {
  Bindings: AppBindings;
  Variables: AppVariables;
};
